# app_key: "ltnzxs5zuv0emel"
# app_secret: "wfl2wvnrjkietdk"
# access_token: "b2vlotdflii9yg61"
# access_token_secret: "rz5tb4gcky24pv0"
# user_id: "168178885"
# access_type: "dropbox"

app_key: "t4et7ezkso0jtsv"
app_secret: "8gfvhxpoy2xck6q"
access_token: "kvut3xgendnlkxqe"
access_token_secret: "lzoy6hhhqm5a03t"
user_id: "168178885"
access_type: "app_folder"